spring.application.name=demo

camel.springboot.main-run-controller=true
camel.springboot.routes-include-pattern = classpath:camel/*.xml
logging.level.org.apache.camel=INFO
logging.level.com.example=INFO

# Aiven Connection Details
camel.component.kafka.brokers=kafka-2541682b-saranyasanand9-bae4.g.aivencloud.com:20449


# Security Protocol
camel.component.kafka.security-protocol=SSL

# Truststore (Server Verification)
# We use "file:" to point to the relative path in your project
camel.component.kafka.ssl-truststore-location=src/main/resources/certs/client.truststore.jks
camel.component.kafka.ssl-truststore-password=password123
camel.component.kafka.ssl-truststore-type=JKS

# Keystore (Client Identity)
camel.component.kafka.ssl-keystore-location=src/main/resources/certs/client.keystore.p12
camel.component.kafka.ssl-keystore-password=password123
camel.component.kafka.ssl-keystore-type=PKCS12
camel.component.kafka.ssl-key-password=password123

# Producer Tuning (Optional but recommended for reliability)
camel.component.kafka.retries=5
camel.component.kafka.request-timeout-ms=30000
