spring.application.name=demo

camel.springboot.main-run-controller=true
camel.springboot.routes-include-pattern = classpath:camel/*.xml
logging.level.org.apache.camel=INFO
logging.level.com.example=INFO
